[project]
name = "policybot"
version = "0.1.0"
description = "Slack bot for Terraform security scanning"
dependencies = [
    "flask==3.0.3",
    "slack-bolt==1.22.0",
    "boto3==1.35.39",
    "checkov==3.2.280",
    "gunicorn==23.0.0"
]

[tool.poetry]